version: '2.1'

services:
  proxy:
    image: local-proxy
    build: .
    volumes:
      - ./proxy.yml:/proxy.yml
    ports:
      - 8080:80
      - 8081:443

networks:
  default:
    external:
      name: trv-studio
