version: '2.1'

services:
  proxy:
    image: local-proxy
    build: .
    volumes:
      - ./proxy.yml:/proxy.yml
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 80:80
      - 8080:443

networks:
  default:
    external:
      name: local-dev
