version: '2.1'
services:
  proxy:
    command: ['debug', 'docker']
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ./src/:/nginx-helper/src/
      - ./bin/:/nginx-helper/bin/
