version: '2.1'

services:
  registrator:
    image: gliderlabs/registrator:v7
    command: ['http://proxy:5000']
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  proxy:
    image: local-proxy
    build: .
    depends_on:
      - registrator
    volumes:
      - ./proxy.yml:/proxy.yml
    ports:
      - 80:80
      - 8081:443
      - 5000:5000

networks:
  default:
    external:
      name: local-dev
